if: branch = master
if: type = pull_request

sudo: required

services:
  - docker

language: generic

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.31.1/hugo_0.31.1_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb

script:
  - hugo
  - docker build -t ${TRAVIS_COMMIT} .
