# Only build pull requests and tags
if: (type = pull_request AND (NOT branch IN (master)) OR (type = tag AND branch = master)

# Using docker, therefore sudo
sudo: required
services:
- docker

# Hugo is a binary that lives in this repo, and we're basically just running shell commands
language: generic

# Env variables
env:
  - REPO_NAME=demo-blog

# Pre-run tasks
before_install:
  - docker login -u=${DOCKER_USERNAME} -p="$DOCKER_PASSWORD"

# Compiling the site, then loading the static bits into a container
jobs:
  include:
  - stage: Build
    script: 
    - bin/build.sh
    - docker build -t ${REPO_NAME}:${TRAVIS_COMMIT} .
    - docker tag ${REPO_NAME}:${TRAVIS_COMMIT} ${DOCKER_USERNAME}/${REPO_NAME}:${TRAVIS_COMMIT}
    - docker push ${DOCKER_USERNAME}/${REPO_NAME}
  - stage: Test
    script:
    - bin/test.sh
  - stage: Tag
    script:
    - docker tag ${DOCKER_USERNAME}:${TRAVIS_COMMIT} ${DOCKER_USERNAME}/${REPO_NAME}:${TRAVIS_BRANCH}
    - docker push ${DOCKER_USERNAME}/${REPO_NAME}

stages:
  - Build
  - Test
  - Tag
