# Only build pull requests, develop, and master when tags are present 
# For tagged releases, push a tagged version of the container
if: (type = pull_request) OR (branch = develop) OR ( (branch = master) AND (tag IS present) )

# Using docker, therefore sudo
sudo: required
services:
- docker

# Hugo is a binary that lives in this repo, and we're basically just running shell commands
language: generic
cache:
  directories:
  - bin

# Compiling the site, then loading the static bits into a container
jobs:
  include:
  - stage: Build
    script: 
    - bin/hugo
    - docker build -t demo-blog:${TRAVIS_COMMIT} .
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker tag demo-blog:${TRAVIS_COMMIT} ${DOCKER_USERNAME}/demo-blog:${TRAVIS_COMMIT}
    - docker push roosri/demo-blog
  - stage: Test
    script:
    - docker run -d -p 80:4567 --rm ${DOCKER_USERNAME}/demo-blog:${TRAVIS_COMMIT}
    - sleep 3 && curl -s localhost:4567 | grep '<!doctype html>'
  - stage: Deploy
    script: echo "Deploy goes here"


stages:
  - Build 
  - Test
  - Deploy
