theme = "kiera"

pygmentsCodeFences = true

disqusShortname = "" #Disqus shortname
googleAnalytics = "" #Google Analytics ID

[author]
    name = "James Loosli"       #Author name
    github = "roosri"     #Github username
    facebook = "jamesbloosli"
    instagram = "jamesloosli"  #Instagram username

[params]
    tagline = "yet another travis demo"
